# Generated by Django 3.2.10 on 2022-03-17 03:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_developer_social_stackoverflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='developer.developer')),
                ('sender', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
            ],
            options={
                'ordering': ['is_read', '-created'],
            },
        ),
    ]
