# Generated by Django 3.2.10 on 2022-03-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_developer_social_stackoverflow'),
        ('project', '0006_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.developer'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('developer', 'project')},
        ),
    ]
